config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_sign_in'
  end

  #メモ：userはシフト投稿とシフト確認のみ
  root to: 'top#top'
  resources :users, only: [:show, :edit, :update, :destroy] do
    get "confirm_shift_posts", on: :member
  end
  resources :shift_posts, except: [:index] 
  
  namespace :admin do
    root to: 'top#top'
    resources :users
    resources :stores
    resources :shift_posts, only: [:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/top_controller.rb
class Admin::TopController < ApplicationController
  def top
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def top
  end
end

app/helpers/admin/top_helper.rb
module Admin::TopHelper
end

app/helpers/user/top_helper.rb
module User::TopHelper
end

app/views/top/top.html.erb
<div class="top-wrapper">
  <div class="box-container">
    <div class="appname-container">
      <h1><span class="under">CELL SHIFT</h1>
    </div>
    <div class="menu-container white">
      <%= link_to new_shift_post_path, {class: "menu-link"} do %><p>シフト希望を提出</p><% end %>
    </div>
    <div class="menu-container blue">
      <%= link_to confirm_shift_posts_user_path(id: current_user.id), {class: "menu-link"} do %><p>シフトを確認</p><% end %>
    </div>
    <div class="discription">
      <p>
        CELL SHIFT(セルシフト)は<br>
        シフトの提出やシフトの確認を<br>
        直感的な操作でできるアプリです。<br>
        毎月の面倒なシフト調整を簡単にします。<br>
        メニューからやることをお選びください。
      </p>
    </div>
  </div>
</div>