config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_sign_in'
  end

  #メモ：userはシフト投稿とシフト確認のみ
  root to: 'top#top'
  resources :users, only: [:show, :edit, :update, :destroy] do
    get "confirm_shift_posts", on: :member
  end
  resources :shift_posts, except: [:index] 
  
  namespace :admin do
    root to: 'top#top'
    resources :users
    resources :stores
    resources :shift_posts, only: [:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :store_users
  has_many :users, through: :store_users
  has_many :admin_users
  has_many :admins, through: :admin_users
  has_many :shift_frames, dependent: :destroy

  accepts_nested_attributes_for :store_users
  accepts_nested_attributes_for :shift_frames, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: { message: "名前を入力してください" }
  validates :need_workers, inclusion: {in:0..3}
  validate  :open_close_check
  validates_associated :shift_frames 

  def open_close_check
    errors.add(:close_at, "営業開始時間より前の時間を登録できません。") unless
    self.open_at < self.close_at
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < ApplicationController
  FORM_COUNT = 3

  def index
    @stores = Store.all
  end

  def new
    @store = Store.new
    FORM_COUNT.times { @store.shift_frames.build }
  end 

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to admin_stores_path
    else
      render :new
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
      redirect_to admin_stores_path
    else
      render :edit
    end
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    redirect_to admin_stores_path
  end

  private

  def store_params
    params.
      require(:store).
      permit(
        :name, :open_at, :close_at, :need_workers,
      shift_frames_attributes: [:id, :shift_name, :start_at, :finish_at]
      )
  end
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/views/admin/stores/edit.html.erb
<div class="store-info-wrapper">
  <h2>店舗情報</h2>
  <div class="form-area">
    <%= form_with model: [:admin, @store], local: true do |f| %>
      <div class="input-field">
        <%= f.label :name, "店舗名" %>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="input-field">
        <%= f.label :business_hour, "営業時間" %>
        <%= f.time_select :open_at, {required: true, prompt: true, ignore_date: true}, {class: "time-select"} %> 〜 <%= f.time_select :close_at, {required: true, prompt: true, ignore_date: true}, {class: "time-select"} %>
      </div>
      <div class="input-field">
        <%= f.label :shift_pattern, "必要人数／日" %>
        <%= f.select :need_workers, {"0":0,"1":1,"2":2,"3":3}, {include_blank: '選択してください', required: true}, {class: "select-box"} %> 人
      </div>
      <%= f.fields_for :shift_frames do |frame| %>
        <div class="input-field">
          <%= frame.label :shift_name, "シフト名" %>
          <%= frame.select :shift_name, {"通し":0,"早":1,"中":2,"遅":3}, {include_blank: '選択してください', required: true}, { class: "select-box"} %>
        </div>
        <div class="input-field">
          <%= frame.label :start_at, "シフト時間" %>
          <%= frame.time_select :start_at, 
          {required: true, include_blank: true, ignore_data:true},
          {class: "time-select"} %> 
          〜 
          <%= frame.time_select :finish_at,
          {required: true, include_blank: true, ignore_data:true}, 
          {class: "time-select"} %>
        </div>
      <% end %>
      <div class="btn-field">
        <%= f.submit "更新", class: "btn update" %>
      </div>
    <% end %>
  </div>
</div>
  

app/views/admin/stores/index.html.erb
<div class="stores-wrapper">
  <div class="above-contents">
    <h2>店舗一覧</h2>
    <%= link_to "店舗を追加", new_admin_store_path, class:"create-store-btn" %>
  </div>
  <div class="stores-container">
    <% @stores.each do |store| %>
      <div class="store-box">
        <h3><span class="under"><%= store.name %></h3>
        <p class="business-hour"><%= store.open_at.strftime( "%-H:%M" ) %>〜<%= store.close_at.strftime( "%-H:%M" ) %></p>
        <p class="link"><%= link_to "シフト確認" %></p>
        <p class="link"><%= link_to "詳細・編集", edit_admin_store_path(store.id) %></p>
        <p class="link">
          <%= link_to "削除", admin_store_path(store.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
        </p>
      </div>
    <% end %>
  </div>
  <div class="under-contents">
    <%= link_to "ホーム", admin_root_path %>
  </div>
</div>
      

app/views/admin/stores/new.html.erb
<div class="store-info-wrapper">
  <h2>店舗情報</h2>
  <div class="form-area">
    <%= form_with model: [:admin, @store], local: true do |f| %>
      <div class="input-field">
        <%= f.label :name, "店舗名" %>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="input-field">
        <%= f.label :business_hour, "営業時間" %>
        <%= f.time_select :open_at, 
        {required: true, prompt: true, ignore_date: true}, 
        {class: "time-select"} %> 
        〜 
        <%= f.time_select :close_at, 
        {required: true, prompt: true, ignore_date: true}, 
        {class: "time-select"} %>
      </div>
      <div class="input-field">
        <%= f.label :shift_pattern, "必要人数／日" %>
        <%= f.select :need_workers, {"0":0,"1":1,"2":2,"3":3}, {include_blank: '選択してください', required: true}, {class: "select-box"} %> 人
      </div>
      <%= f.fields_for :shift_frames do |frame| %>
        <div class="input-field">
          <%= frame.label :shift_name, "シフト名" %>
          <%= frame.select :shift_name, {"通し":0,"早":1,"中":2,"遅":3}, {include_blank: '選択してください', required: true}, { class: "select-box"} %>
        </div>
        <div class="input-field">
          <%= frame.label :start_at, "シフト時間" %>
          <%= frame.time_select :start_at, 
          {required: true, include_blank: true},
          {class: "time-select"} %> 
          〜 
          <%= frame.time_select :finish_at,
          {required: true, include_blank: true}, 
          {class: "time-select"} %>
        </div>
      <% end %>
      
      <div class="btn-field">
        <%= f.submit "登録", class: "btn create" %>
      </div>
    <% end %>
  </div>
</div>