config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_sign_in'
  end

  #メモ：userはシフト投稿とシフト確認のみ
  root to: 'top#top'
  resources :users, only: [:show, :edit, :update, :destroy] do
    get "confirm_shift_posts", on: :member
  end
  resources :shift_posts, except: [:index] 
  
  namespace :admin do
    root to: 'top#top'
    resources :users
    resources :stores
    resources :shift_posts, only: [:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :store_users
  has_many :stores, through: :store_users
  has_many :shift_posts

  validates :name, presence: { message: "名前を入力してください" }
  VALID_EMAIL_REGEX = /\A[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*\z/
  validates :email, presence: true, 
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false, unless: :guest_admin_email? }
  validates :shift_stabilize, inclusion: {in:0..3}, 
                              presence:  { message: "専門シフトの有無を入力してください" },
                              on: :update
  # WDAY_TEXT = ["日","月","火","水","木","金","土","特になし"]
  # validates :wday, inclusion: {in: WDAY_TEXT}
  validates :max_work, inclusion: {in:0..3}, on: :update
  validates :wages, numericality: {greater_than_or_equal_to: 1_113	}, on: :update

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー',
                       email: 'guest@example.com',
                       shift_stabilize: 0,
                      #  wday: '特になし',
                       max_work: 3 ,
                       wages: 1300) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.guest_admin
    find_or_create_by!(name: 'ゲスト管理者',
                       email: 'guest_admin@example.com',
                       shift_stabilize: 0,
                      #  wday: '特になし',
                       max_work: 3,
                       wages: 1500,
                       admin: true) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def guest_admin_email?
    email == 'guest_admin@example.com'
  end

  def shift_stabilize_text
    case shift_stabilize
    when 0
      "特になし"
    when 1
      "早番"
    when 2
      "中番"
    when 3
      "遅番"
    else
      "不明な値"
    end
  end

  def wday_text
    case wday
    when 0
      "日"
    when 1
      "月"
    when 2
      "火"
    when 3
      "水"
    when 4
      "木"
    when 5
      "金"
    when 6
      "土"
    else
      "特になし"
    end
  end

  def max_work_text
    case max_work
    when 0
      "２日"
    when 1
      "３日"
    when 2
      "４日"
    when 3
      "５日"
    else
      "特になし"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin

  def index
    @users = User.includes(:stores)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(profile_params)
      if current_user.admin?
        redirect_to admin_root_path
      else
        redirect_to root_path
      end
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def profile_params
    params.require(:user).permit(:name, :shift_stabilize, :max_work, :wages, :holiday, :priority, wday: [], store_ids: [])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  
  protected
  
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    if params[:admin] == "true"
      user = User.guest_admin
    else
      user = User.guest
    end
    sign_in user
    redirect_to user.admin? ? admin_root_path : root_path, notice: 'ゲストとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_normal_user, only: %i[update destroy]
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(profile_params)
      if current_user.admin?
        redirect_to admin_root_path
      else
        redirect_to root_path
      end
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.email == 'guest@example.com' || @user.email == 'guest_admin@example.com'
      reset_session
      redirect_to :root
    else
      @user.update(is_valid: false)
      reset_session
      redirect_to new_user_session_path
    end
  end

  def confirm_shift_posts
    @user = User.find(params[:id])
    @shift_posts_by_date = @user.shift_posts.group_by { |sp| sp.selected_dates }
  end

  def ensure_normal_user
    @user = User.find(params[:id])
    if @user.email == 'guest@example.com' || @user.email == 'guest_admin@example.com'
      if current_user.admin?
        redirect_to admin_root_path, alert: 'ゲストユーザーの更新・削除はできません。' and return
      else
        redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。' and return
      end
    end
  end


  private

  def profile_params
    params.require(:user).permit(:name, :shift_stabilize, :max_work, :wages, :holiday, :priority, wday: [], store_ids: [])
  end
end

app/helpers/user/top_helper.rb
module User::TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="profile-container">
  <div class="profile-box">
    <h3>プロフィール</h3>
    <%= form_with model: @user, method: "patch", local: true do |f| %>
      <div class="input-field">
        <%= f.label :name, "名前" %>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="input-field">
        <%= f.label :shift_stabilize, "専門シフト" %>
        <%= f.select :shift_stabilize, {"特になし":0,"早":1,"中":2,"遅":3}, {include_blank: '選択してください', required: true}, { class: "select-box"} %>
      </div>
      <div class="input-field">
        <%= f.label :wday, "出勤不可曜日" %></br>
        <% ["日","月","火","水","木","金","土","特になし"].each_with_index do |wday,i| %>
          <%= f.check_box :wday, {multiple: true}, i, nil %>
          <%= wday %>
        <% end %>
      </div>
      <div class="input-field">
        <%= f.label :max_work, "週◯日？" %>
        <%= f.select :max_work, {"2":0,"3":1,"4":2,"5":3}, {include_blank: '選択してください', required: true}, {class: "select-box"} %> 回
      </div>
      <div class="input-field">
        <%= f.label :stores, "シフトイン可能店舗" %></br>
        <%= f.collection_check_boxes( :store_ids, Store.all, :id, :name ) %>
      </div>
      <div class="input-field">
        <%= f.label :wages, "時給" %>
        <%= f.number_field :wages, {min: 1100, class: "select-box"} %>
      </div>
      <div class="input-field">
        <%= f.label :holiday, "土日祝勤務可否" %>
        <%= f.check_box :holiday, {class: "select-box"}, true, false %>
      </div>
      <div class="input-field">
        <%= f.label :holiday, "シフト優先者" %>
        <%= f.check_box :priority, {class: "select-box"}, true, false %>
      </div>
      <div class="btn-field">
        <%= f.submit "更新", class: "btn update" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="index-container">
  <h3>スタッフ一覧</h3>
  <table>
    <thead>
      <tr>
        <th>名前</th>
        <th>担当店舗</th>
        <th>時給</th>
        <th>シフト確認</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><span class="mini-label">担当店舗</span><%= user.stores.name %></td>
          <td><span class="mini-label">時給</span><%= user.wages %></td>
          <td><%= link_to "確認する", "#" %></td>
          <td><%= link_to "編集する", admin_user_path(user.id) %></td>
          <td>
            <%= link_to "削除する", user_path(user.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table> 
</div>

app/views/admin/users/show.html.erb
<div class="profile-container">
  <div class="profile-box">
    <h3><%= @user.name %> さんのプロフィール</h3> 
    <table>
      <tr>
        <td>時給</td><td><%= @user.wages %></td>
      </tr>
      <tr>
        <td>専門シフト</td><td><%= @user.shift_stabilize_text %></td>
      </tr>
      <tr>
        <td>出勤不可曜日</td><td><%= @user.wday_text %></td>
      </tr>
      <tr>
        <td>最大週日数</td><td><%= @user.max_work_text %></td>
      </tr>
      <tr>
        <td>土日祝勤務</td>
        <td>
          <% if @user.holiday == true %>
            あり
          <% else %>
            なし
          <% end %>
        </td>
      </tr>
      <tr>
        <td>シフトイン可能店舗</td>
        <td>
          <% @user.store_users.each do |store_user| %>
            <p><%= store_user.store.name %></p>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>シフト優先者</td>
        <td>
          <% if @user.priority == true %>
            対象
          <% else %>
            対象外
          <% end %>
        </td>
      </tr>
    </table>
    <div>
      <%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn-to-edit" %>
      <%= link_to "ホーム", current_user.admin? ? admin_root_path : root_path, class: "btn-to-top" %>
    </div>
  </div>
  <div>
    <%= link_to "ユーザー名、パスワードの変更はこちらから", edit_user_registration_path %>
  </div>
</div>