config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_sign_in'
  end

  #メモ：userはシフト投稿とシフト確認のみ
  root to: 'top#top'
  resources :users, only: [:show, :edit, :update, :destroy] do
    get "confirm_shift_posts", on: :member
  end
  resources :shift_posts, except: [:index] 
  
  namespace :admin do
    root to: 'top#top'
    resources :users
    resources :stores
    resources :shift_posts, only: [:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CellShift</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-left">
        <%= link_to "CELL SHIFT", user_signed_in? && current_user.admin? ? admin_root_path : root_path %>
      </div>
      <div class="header-right">
        <% if user_signed_in? %>  
            <div class="menu-trigger">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="navigation">
              <% if current_user.admin? %>
                <ul>
                  <li><%= link_to "シフト", admin_shift_posts_path(id: current_user.id) %></li>
                  <li><%= link_to "店舗", admin_stores_path %></li> 
                  <li><%= link_to "スタッフ", admin_users_path %></li>
                  <li><%= link_to "アカウント", admin_user_path(id: current_user.id) %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                </ul>
              <% else %>
                <ul>
                  <li><%= link_to "シフト", confirm_shift_posts_user_path(id: current_user.id) %></li>
                  <li><%= link_to "アカウント", user_path(id: current_user.id) %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                </ul>
              <% end %>
            </div>
        <% else %>
          <%= link_to "ログイン", new_user_session_path,  class: "link login" %>
          <%= link_to "新規登録", new_user_registration_path,  class: "link signup" %>
        <% end %>
      </div>
    </header>
    <main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <footer>
      <p>© <%= Time.current.year %> CELL SHIFT</p>
    </footer>
  </body>
</html>